/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ionescugiuliamariameteo;

import com.google.gson.Gson;
import java.awt.Color;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author giuli
 */
public class FrameMeteo extends javax.swing.JFrame {

    /**
     * Creates new form FrameMeteo
     */
    public FrameMeteo() {
        initComponents();
        atxrisultato.setVisible(false);
        this.getContentPane().setBackground(new Color(135, 206, 250));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblcitta = new javax.swing.JLabel();
        txtcitta = new javax.swing.JTextField();
        btncerca = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        atxrisultato = new javax.swing.JTextArea();
        lblIcona = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Meteo");

        lblcitta.setText("Cerca la cittá per vedere il meteo:");

        btncerca.setText("Cerca");
        btncerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncercaActionPerformed(evt);
            }
        });

        atxrisultato.setColumns(20);
        atxrisultato.setRows(5);
        jScrollPane1.setViewportView(atxrisultato);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(lblIcona))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btncerca)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(130, 130, 130)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblcitta)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtcitta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcitta)
                    .addComponent(txtcitta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(btncerca)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblIcona)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncercaActionPerformed
        try {
            String apiKey = "d689285e408b211c2e279fa60fcf9dc5";
            String citta = txtcitta.getText();
            //OpenWeathere non accetta gli spazi, accenti e caratteri speciali, quindi si utilizza un endcoder così troviamo la città scelta
            String encodedCitta = URLEncoder.encode(citta, StandardCharsets.UTF_8);
            String urlString = "https://api.openweathermap.org/data/2.5/weather?q=" + encodedCitta + "&appid=" + apiKey + "&units=metric&lang=it";
            URL url = new URL(urlString);
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("GET");
            BufferedReader br = new BufferedReader(new InputStreamReader(conn.getInputStream()));
            StringBuilder response = new StringBuilder();
            String line;
            while ((line = br.readLine()) != null) {
                response.append(line);
            }
            br.close(); // Converte JSON → Oggetto Radice 
            Gson gson = new Gson();
            Radice root = gson.fromJson(response.toString(), Radice.class); // Stampa alcuni dati 
            atxrisultato.setVisible(true);
            atxrisultato.setText("");
            atxrisultato.append("Citta: " + root.name + "\n");
            atxrisultato.append("Temperatura: " + root.main.temp + "°C" + "\n");
            atxrisultato.append("Descrizione: " + root.weather.get(0).description + "\n");
            atxrisultato.append("Umidità: " + root.main.humidity + "%" + "\n");
            atxrisultato.append("Vento: " + root.wind.speed + " m/s" + "\n");
            String iconCode = root.weather.get(0).icon;
            String iconUrl = "http://openweathermap.org/img/wn/" + iconCode + "@2x.png";

            // Prende l'immagine
            ImageIcon icon = new ImageIcon(new URL(iconUrl));

            // Se voglio ridimensionarla
            Image scaled = icon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
            ImageIcon scaledIcon = new ImageIcon(scaled);

            // Mette l'icona nella JLabel
            lblIcona.setIcon(scaledIcon);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"C'é stato un errore nel cercare la cittá scelta, controllare di aver scritto bene","Errore",JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btncercaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea atxrisultato;
    private javax.swing.JButton btncerca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIcona;
    private javax.swing.JLabel lblcitta;
    private javax.swing.JTextField txtcitta;
    // End of variables declaration//GEN-END:variables
}
